FROM node:alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

ARG STORE_CORS=${STORE_CORS}
ARG ADMIN_CORS=${ADMIN_CORS}
ARG AUTH_CORS=${AUTH_CORS}
ARG REDIS_URL=${REDIS_URL}
ARG JWT_SECRET=${JWT_SECRET}
ARG COOKIE_SECRET=${COOKIE_SECRET}
ARG DATABASE_URL=${DATABASE_URL}
ARG DB_NAME=${DB_NAME}
ARG POSTGRES_URL=${POSTGRES_URL}

ENV STORE_CORS=${STORE_CORS}
ENV ADMIN_CORS=${ADMIN_CORS}
ENV AUTH_CORS=${AUTH_CORS}
ENV REDIS_URL=${REDIS_URL}
ENV JWT_SECRET=${JWT_SECRET}
ENV COOKIE_SECRET=${COOKIE_SECRET}
ENV DATABASE_URL=${DATABASE_URL}
ENV DB_NAME=${DB_NAME}
ENV POSTGRES_URL=${POSTGRES_URL}

RUN npx medusa db:create

RUN npx medusa user --email asilormail@gmail.com --password password

RUN yarn seed

RUN npx medusa db:migrate

RUN npx medusa build

RUN npx medusa telemetry --disable

EXPOSE 9000

CMD ["npx", "medusa", "start"]